name: Detailed Bug Report
description: Submit a structured bug report with dropdowns, checkboxes, and contact info.
title: "[BUG]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we reach you if we need more info?
      placeholder: ex. email@example.com

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen, and what actually happened?
      placeholder: Tell us what you saw and expected.
      value: "A bug happened!"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How bad is the issue?
      options:
        - Low
        - Medium
        - High
        - Critical
      default: 1
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: App Version
      description: What version of the app are you using?
      options:
        - Dev (Default)
        - 1.0.0 (Edge)
      default: 0
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: Browsers affected (if relevant)
      description: Select all that apply
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Describe the exact steps to trigger the bug
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Paste relevant logs. Auto-formatted as code.
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
	description: By submitting, you agree to our [Code of Conduct](../CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
